baseURL = 'https://robin-vidal.com/'
languageCode = 'en-us'
title = 'Robin Vidal'

[params]
  # GoatCounter instance, without trailing slash. Empty disables analytics.
  goatcounter = 'https://goatcounter.robin-vidal.com'
  github = 'https://github.com/robin-vidal'
  resume = '/resume.pdf'
  linkedin = 'https://www.linkedin.com/in/robin-vidal-jml/'

[markup.goldmark.renderer]
  unsafe = true
