baseURL = 'https://robin-vidal.com/'
languageCode = 'en-us'
title = 'Robin Vidal'

[params]
  # GoatCounter instance, without trailing slash. Empty disables analytics.
  goatcounter = 'https://goatcounter.robin-vidal.com'
  github = '/github'
  resume = '/resume.pdf'
  linkedin = '/linkedin'

[markup.goldmark.renderer]
  unsafe = true
