replicaCount: 1

image:
  repository: ghcr.io/robin-vidal/personal-site
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: robin-vidal.com
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
