apiVersion: v1
kind: Service
metadata:
  name: {{ include "personal-site.fullname" . }}
  labels:
    {{- include "personal-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "personal-site.selectorLabels" . | nindent 4 }}
